apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jira-to-slack
spec:
  rules:
  - host: jira-to-slack.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: jira-to-slack
          servicePort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: jira-to-slack
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    app: jira-to-slack
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jira-to-slack
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jira-to-slack
    spec:
      containers:
      - name: jita-to-slack
        image: int128/jira-to-slack:1.0
        env:
        - name: SLACK_WEBHOOK
          value: https://hooks.slack.com/example
        - name: SLACK_USERNAME
          value: JIRA
        ports:
        - name: http
          containerPort: 3000
        resources:
          limits:
            memory: 128Mi
          requests:
            memory: 128Mi
            cpu: 500m
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 10
          timeoutSeconds: 5
