version: 2
jobs:
  app:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/int128/jira-to-slack
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go get github.com/golang/lint/golint
      - run: golint
      - run: go test -v

  helm:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: helm-github-pages
          command: wget -O - https://raw.githubusercontent.com/int128/helm-github-pages/master/publish.sh | sh
          environment:
            - GITHUB_PAGES_REPO: int128/helm-charts

  release:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/int128/jira-to-slack
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go get github.com/mitchellh/gox
      - run: go get github.com/tcnksm/ghr
      - run: gox --osarch 'darwin/amd64 linux/amd64 windows/amd64' -output 'dist/{{.Dir}}_{{.OS}}_{{.Arch}}'
      - run: ghr -u "$CIRCLE_PROJECT_USERNAME" -r "$CIRCLE_PROJECT_REPONAME" "$CIRCLE_TAG" dist

workflows:
  version: 2
  build:
    jobs:
      - app
      - helm
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
